### ISSUE TITLE
help 

### ISSUE THREAD

**Issue by ultra7083** [sicxu/Deep3dPortrait#20]
hello everybody 

Traceback (most recent call last):
  File "step1_recon_3d_face.py", line 10, in <module>
    from utils.create_renderer import create_renderer_graph
  File "/Deep3dPortrait/utils/create_renderer.py", line 2, in <module>
    from .render.mesh_renderer import mesh_renderer
  File "/Deep3dPortrait/utils/render/mesh_renderer.py", line 24, in <module>
    from .rasterize_triangles import rasterize_triangles
  File "/Deep3dPortrait/utils/render/rasterize_triangles.py", line 27, in <module>
    os.path.dirname(os.path.abspath(__file__)),'kernels/rasterize_triangles_kernel_1.so'))
  File "/home/pc/.local/lib/python3.5/site-packages/tensorflow_core/python/framework/load_library.py", line 61, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: libtensorflow_framework.so: cannot open shared object file: No such file or directory

this is my return when i use a commade

step1_recon_3d_face.py

I hope I could find some help we are already a few days in the search

**Comment by ultra7083** [comment]
hi for a people see this message.

my error change in this 


pc@pc-A:~/Deep3dPortrait$ sudo python3 step1_recon_3d_face.py [sudo] Mot de passe de pc : 
Traceback (most recent call last):
  File "step1_recon_3d_face.py", line 10, in <module>
    from utils.create_renderer import create_renderer_graph
  File "/home/pc/Deep3dPortrait/utils/create_renderer.py", line 2, in <module>
    from .render.mesh_renderer import mesh_renderer
  File "/home/pc/Deep3dPortrait/utils/render/mesh_renderer.py", line 24, in <module>
    from .rasterize_triangles import rasterize_triangles
  File "/home/pc/Deep3dPortrait/utils/render/rasterize_triangles.py", line 27, in <module>
    os.path.dirname(os.path.abspath(__file__)),'kernels/rasterize_triangles_kernel_1.so'))
  File "/usr/local/lib/python3.5/dist-packages/tensorflow_core/python/framework/load_library.py", line 61, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: libtensorflow_framework.so: cannot open shared object file: No such file or directory


i think maybee i install in wrong direction or i miss a step 

if one people can help me is my hero for my year 

because we are two artist we lot of hope run this code for make art 


if one people want to give a little help on this project is powerfull help for me and my freind 


i write here  because about this recent code we dont find lot of help 


pllease this is a bottle in a sea 

have a good night for all and thx for u if u just are reading this thx thx thx

**Comment by ultra7083** [comment]
if one people see where i make a wrong action or bad installation its pleasure to received an big help 

have a good night for all a next time

**Comment by sicxu** [comment]
Could  u provide more info about your environment? such as tensorflow version, cuda version, etc.

**Comment by JunHanStudy** [comment]
@ultra7083 I have the same problem. Did you solve it?

**Comment by bobxin123** [comment]
hello everybody

python step1_recon_3d_face.py

Traceback (most recent call last):
  File "step1_recon_3d_face.py", line 10, in <module>
    from utils.create_renderer import create_renderer_graph
  File "/home/zqh/anaconda3/envs/tensorflow1.12/Deep3dPortrait-master/utils/create_renderer.py", line 2, in <module>
    from .render.mesh_renderer import mesh_renderer
  File "/home/zqh/anaconda3/envs/tensorflow1.12/Deep3dPortrait-master/utils/render/mesh_renderer.py", line 24, in <module>
    from .rasterize_triangles import rasterize_triangles
  File "/home/zqh/anaconda3/envs/tensorflow1.12/Deep3dPortrait-master/utils/render/rasterize_triangles.py", line 26, in <module>
    rasterize_triangles_module = tf.load_op_library(os.path.join(
AttributeError: module 'tensorflow' has no attribute 'load_op_library'

this is my return when i use a commade

step1_recon_3d_face.py

I hope I could find some help we ,thanks

my environment:
tensorflow1.12
cudatoolkit==9.2.0
cudnn==7.6.5

**Comment by avgAnimeOtaku** [comment]
> hello everybody
> 
> python step1_recon_3d_face.py
> 
> Traceback (most recent call last): File "step1_recon_3d_face.py", line 10, in from utils.create_renderer import create_renderer_graph File "/home/zqh/anaconda3/envs/tensorflow1.12/Deep3dPortrait-master/utils/create_renderer.py", line 2, in from .render.mesh_renderer import mesh_renderer File "/home/zqh/anaconda3/envs/tensorflow1.12/Deep3dPortrait-master/utils/render/mesh_renderer.py", line 24, in from .rasterize_triangles import rasterize_triangles File "/home/zqh/anaconda3/envs/tensorflow1.12/Deep3dPortrait-master/utils/render/rasterize_triangles.py", line 26, in rasterize_triangles_module = tf.load_op_library(os.path.join( AttributeError: module 'tensorflow' has no attribute 'load_op_library'
> 
> this is my return when i use a commade
> 
> step1_recon_3d_face.py
> 
> I hope I could find some help we ,thanks
> 
> my environment: tensorflow1.12 cudatoolkit==9.2.0 cudnn==7.6.5

Same error is returned when I ran it, have you solved it?
